Algoritmo "EXE09"
// Disciplina   : [ Lógica de Programação]
// Professor   : Jailson Costa
// Descrição   : EXE(7I) Ler dois inteiros (variáveis A e B) e
// imprimir o resultado do quadrado da diferença do primeiro valor pelo
// segundo.
// Autor(a)    : João Victor
// Data atual  : 22/09/2026
Var
// Seção de Declarações das variáveis 
A,B,resultado: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval ("Digite o valo A: ")
leia(A)
escreval ("Digite o valor B: ")
leia(B)
resultado<- (a - b) * (a - b)
escreval("o resultado do quadrado é: ", resultado)


Fimalgoritmo