Algoritmo "EXE07"
// Disciplina   : [Lógica de Programação]
// Professor   :Jailson Costa 
// Descrição   : (EXE7G)Ler quatro números inteiros e apresentar o resultado
//da adição e multiplicação, baseando-se na utilização do conceito da
// propriedade distributiva. Ou seja, se forem lidas as variáveis A, B,
// C, e D, devem ser somadas e multiplicadas A com B, A com C e A com D
// Depois B com C, B com D e por fim C com D. Perceba que será
// necessário efetuar seis operações de adição e seis operações de
// multiplicação e apresentar doze resultados de saída
// Autor(a)    : João Victor
// Data atual  : 22/09/2026
Var
// Seção de Declarações das variáveis 
A,B,C,D:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite o valor de A: ")
leia(A)
escreval("Digite o valor de B: ")
leia(B)
escreval("Digite o valor de C: ")
leia(C)
escreval("Digite o valor de D: ")
leia(D)
escreval("Soma de A com B: ", A + B)
escreval("Multiplicação de A com B: ", a * b)
 escreval("")
escreval("Soma de A com C: ", A + C)
escreval("Multiplicação de A com C: ", a * c)
 escreval("")
escreval("Soma de A com D: ", A + D)
escreval("Multiplicação de A com D: ", a * d)
escreval("")
escreval("Soma de B com C: ", B + C)
escreval("Multiplicação de B com C: ", B * C)
escreval("")
escreval("Soma de B com D: ", B + D)
escreval("Multiplicação de B com D: ", B * D)
escreval("")
escreval("Soma de C com D: ", C + D)
escreval("Multiplicação de C com D: ", C * D)


Fimalgoritmo