Algoritmo "EXE11"
// Disciplina   : [ Lógica de Programação]
// Professor   : Jailson Costa
// Descrição   : EXE(7K) Elaborar um programa que efetue a apresentação
// do valor da conversão em dólar de um valor lido em real.
// O programa deve solicitar o valor da cotação do dólar e também a
// quantidade de reais disponível com o usuário, para que seja
// apresentado o valor em moeda americana.

// Autor(a)    : João Victor
// Data atual  : 22/09/2026
Var
// Seção de Declarações das variáveis 
cotacaoDolar, quantidadeReais,valorEmDolares: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval ("Digite o valor da cotação do dolar: ")
leia(cotacaoDolar)
escreval ("Quantidade de reais disponíveis: ")
leia(quantidadeReais)

valorEmDolares<- quantidadereais / cotacaoDolar
escreval("A quantidade em dolares é: ", valorEmDolares)




Fimalgoritmo