Algoritmo "EXE12"

// Disciplina   : [ Lógica de Programação]

// Professor   : Jailson Costa

// Descrição   : EXE(7L) Elaborar um programa que efetue a leitura de

//  três valores (A, B e C) e apresente como resultado final à soma dos

//  quadrados dos três valores lidos.

// Autor(a)    : João Victor

// Data atual  : 22/09/2026

Var

// Seção de Declarações das variáveis

A, B,C,resultado: real



Inicio

// Seção de Comandos, procedimento, funções, operadores, etc...

escreval ("Digite o valor de (A): ")

leia(A)

escreval ("Digite o valor de (B): ")

leia(B)

escreval ("Digite o valor de (C): ")

leia(C)

resultado<- ((A * A)+ (B * B)+ (C * C))

escreval("o resultado dos quadrados dos 3 valores lidos é: ", resultado)





Fimalgoritmo

