Algoritmo "EXE16"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson Costa
// Descrição   : (EXE1D)Apresentar os resultados das potências de 3,
// variando do expoente 0 até o expoente 15. Deve ser considerado que
// qualquer número elevado a zero é 1, e elevado a 1 é ele próprio.
// Observe que neste exercício não pode ser utilizado o operador de
// exponenciação do portuguol (^).
// Autor(a)    : João Victor
// Data atual  : 22/09/2026
Var
 contadora,multiplicador: inteiro

Inicio
multiplicador <- 1
   escreval("3 elevado a 0 = ", multiplicador)
para contadora de 1 ate 15 faca
multiplicador<- multiplicador*3
escreval(multiplicador)
fimpara

Fimalgoritmo