Algoritmo "EXE13"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson Costa
// Descrição   : (EXE1A)Apresentar a tabuada de um número usando laço
// de repetição
// Autor(a)    : João Victor
// Data atual  : 22/09/2026
Var
numero, contadora: inteiro

Inicio
escreval("Digite um numero para saber sua tabuada: ")
leia(numero)

para contadora de 1 ate 10 faca
   escreval(numero, " x ", contadora, " = ", numero * contadora)
fimpara

Fimalgoritmo