Algoritmo "EXE15"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson Costa
// Descrição   : (EXE1C)Elaborar um programa que apresente no final o
// somatório dos valores pares existentes na faixa de 1 até 500.
// Autor(a)    : João Victor
// Data atual  : 22/09/2026
Var
contadora, soma: inteiro

Inicio
soma<- 0

para contadora de 0 ate 500 passo 2 faca
soma<-soma + contadora
   escreval(contadora)
   fimpara


Fimalgoritmo