Algoritmo "EXE38"
// Disciplina   : [Lógica de Programação]
// Professor    : Jailson Costa
// Descrição    : (EXE5.6.1E) > Apresentar todos os valores numéricos inteiros ímpares situados na faixa de 0 a 20. Para verificar se o número é ímpar, efetuar dentro da malha a verificação lógica desta condição com a instrução se, perguntando se o número é ímpar; sendo, mostre-o; não sendo, passe para o próximo passo.
// Autor(a)     : João Victor
// Data atual   : 27/09/2026
Var
// Seção de Declarações das variáveis
contadora: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
para contadora de 0 ate 20 faca
   se contadora mod 2 <> 0 entao
      escreval(contadora)
   fimse
fimpara

Fimalgoritmo