Algoritmo "EXE34"
// Disciplina   : [Lógica de Programação]
// Professor    : Jailson Costa
// Descrição    : (EXE5.6.1A) > Apresentar os quadrados dos números inteiros de 15 a 200.
// Autor(a)     : João Victor
// Data atual   : 27/09/2026
Var
// Seção de Declarações das variáveis
contadora: inteiro
quadrado: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
para contadora de 15 ate 200 faca
   quadrado <- contadora * contadora
   escreval("Quadrado de ", contadora, " = ", quadrado)
fimpara

Fimalgoritmo